### ISSUE TITLE
I want to request you one feature based on this feature

### ISSUE THREAD

**Issue by PriyankaVithaniLahagora** [pushpendra996/avplayer-swift-part-2-ios#1]

**Comment by PriyankaVithaniLahagora** [comment]
I want to toggle between fullscreen on and off using button at the bottom right corner of the video player
can you please update it?

**Comment by pushpendra996** [comment]
Hello @PriyankaVithaniLahagora Thank you for following my approach I am really happy to see you have raised your query. Here please find the solution as per your requirement. I am glad to help you on this! 
LINK - https://github.com/pushpendra996/avplayer-swift-part-3-ios

**Comment by pushpendra996** [comment]
Hello @PriyankaVithaniLahagora Thank you for following my approach I am really happy to see you have raised your query. Here please find the solution as per your requirement. I am glad to help you on this! 

Video - https://youtu.be/MR6GweE64ho
LINK - https://github.com/pushpendra996/avplayer-swift-part-3-ios

Please subscribe my channel for more upcoming videos!
